### ISSUE TITLE
IE11 STATE_ENCRYPTION_KEY decode error 

### ISSUE THREAD

**Issue by rhoerbe** [IdentityPython/SATOSA#164]
Sign on to test.ucom.gv.at failing with "ValueError: Error 65537 while instatiating the CBC mode" when calling _load_state() in satosa.base. (Being then generalized into satosa.exception.SATOSAUnknownError)

I observed that IE11 includes and empty STATE_ENCRYPTION_KEY cookie , causing the decrypt code in cookie_to_state() to fail with an exception that is not catched in _load_state.

```
...
return CbcMode(cipher_state, iv)
File "/opt/satosa/lib/python3.5/site-packages/Cryptodome/Cipher/_mode_cbc.py", line 101, in init
% result)
ValueError: Error 65537 while instatiating the CBC mode

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/opt/satosa/lib/python3.5/site-packages/satosa/proxy_server.py", line 113, in call
resp = self.run(context)
File "/opt/satosa/lib/python3.5/site-packages/satosa/base.py", line 277, in run
raise SATOSAUnknownError("Unknown error") from err
satosa.exception.SATOSAUnknownError: Unknown error
```

**Comment by leifj** [comment]
This is only IE11?

**Comment by rhoerbe** [comment]
We have not done cross-browser testing yet. The client is only using IE11 and FF.

**Comment by leifj** [comment]
asking for a bit of review of this...

**Comment by skoranda** [comment]
@rhoerbe Can you clarify if this is only observed with IE11 or if it is observed with browsers in addition to IE11? Also, can you specify a particular version or IE11? Thanks.

**Comment by rhoerbe** [comment]
This was IE11 only. I tested with FF and Safari as well.

**Comment by c00kiemon5ter** [comment]
I tried to reproduce this with an [IE11-vagrant-vm][vm] but couldn't. Either way, I changed the PR and I think it can be merged. If you have any comments, let me know soon; otherwise I will merge it towards the end of the week.

  [vm]: https://app.vagrantup.com/modernIE/boxes/w7-ie11

**Comment by rhoerbe** [comment]
Thanks for your clean up, now this is quite shiny code :-) 

Please go ahead with the merge
