### ISSUE TITLE
Static attributes not return in SAML assertions

### ISSUE THREAD

**Issue by toddschilling** [IdentityPython/SATOSA#201]
I am trying to inject 2 static attributes into the SAML assertions returned by the proxy.  I've configured the proxy to use a static_attributes.yaml in the microservices section and can see that it's being loaded at startup.   I've also updated the internal_attributes.yaml config file to reference the keys provided by static_attributes.  What am I missing?

## Code Version
```
Name: SATOSA
Version: 3.4.8
Summary: Protocol proxy (SAML/OIDC).
Home-page: https://github.com/SUNET/SATOSA
Author: DIRG
Author-email: satosa-dev@lists.sunet.se
License: Apache 2.0
Location: /usr/local/lib/python3.6/dist-packages
Requires: Werkzeug, pyop, pycryptodomex, PyYAML, pysaml2, requests, gunicorn, click, pystache
```

## Expected Behavior
Static attributes should be returned in the SAML assertion.

## Current Behavior
Static attributes are missing from the SAML assertion.

## Possible Solution
I probably have something incorrectly configured and just need another set of eyes.

[1-10-2019 9-42.txt](https://github.com/IdentityPython/SATOSA/files/2746473/1-10-2019.9-42.txt)
[internal_attributes.txt](https://github.com/IdentityPython/SATOSA/files/2746467/internal_attributes.txt)
[proxy_conf.txt](https://github.com/IdentityPython/SATOSA/files/2746468/proxy_conf.txt)
[static_attributes.txt](https://github.com/IdentityPython/SATOSA/files/2746469/static_attributes.txt)

**Comment by toddschilling** [comment]
I'm definitely missing something.  If I change a saml attribute name in the internal_attributes.txt file, rather than return an attribute of a different name, it simply removes it from the output.  For example, given the following example, i would expect the SAML output to include an attribute called test that is mapped from openid nickname.  Instead, the attribute test is simply omitted.

`
  displayname:
    openid: [nickname]
    orcid: [name.credit-name]
    github: [login]
    saml: [test]
`

**Comment by c00kiemon5ter** [comment]
Hi, from the attached log file (`1-10-2019 9-42.txt`) I see:

> [2019-01-10 17:28:33] [DEBUG]: no attribute mapping found for internal attribute 'type' the attribute profile 'openid'
> [2019-01-10 17:28:33] [DEBUG]: no attribute mapping found for internal attribute 'group' the attribute profile 'openid'

This means that the appropriate entry is missing from the `internal_attributes.yaml` configuraiton file. From the attached `internal_attributes.txt` file, I see:

```yaml
attributes:
  type:
    saml: [type]
  group:
    saml: [group]
  # more entries ...
```

When attributes are received they are mapped to the internal names as directed by the internal_attributes configuration. Then, those are updated with the ones defined in the `static_attributes` configuraiton. Now, the attributes need to be mapped back to another protocol.
In your case, it seems that you are mapping them back to OIDC (the attribute profile is `openid`). Add the appropriate entries for `openid` (the claims that should hold those values) and the flow should continue as expected:

```yaml
attributes:
  type:
    saml: [type]
    openid: [type]
  group:
    saml: [group]
    openid: [group]
  # more entries ...
```
