### ISSUE TITLE
satosa-saml-metadata creates broken XML

### ISSUE THREAD

**Issue by rhoerbe** [IdentityPython/SATOSA#210]
X509Certificate elements in generated metadata include "-----END CERTIFICATE-----" 

## Code Version
3.4.8

## Expected Behavior
correct XML

## Current Behavior
see above

## Possible Solution
I did not yet track down the issue. I guess it is related with pysaml2 

## reproduce

checkout https://github.com/identinetics/d-satosa/commit/1ab6c6a85b3adc2e62460a47564a70767828688e

build image
run container
bash /opt/test/wpv/setup_testdata.sh
/opt/bin/start.sh

**Comment by peppelinux** [comment]
I did not get this problem in my context, [it's here](https://github.com/peppelinux/Satosa-saml2saml).
I used lastest master branch of satosa and pysaml2

**Comment by rhoerbe** [comment]
bug disappeared (at some point p to V4.4.0)
