### ISSUE TITLE
[Error Handling] Users read "Unknow Error" if SATOSA session is expired

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/SATOSA#228]
If an end user session is expired the user can go from DS to SATOSA to selected IdP anyway, and then do auth, then come back to SATOSA but get "Unknow Error".

Using [this silly patch](https://github.com/IdentityPython/SATOSA/pull/221) I can repr the error to the users, the message would be "Unknown error: 'SATOSA_BASE'".

## Code Version
master branch, current stable

## Expected Behavior
Probably a better handling of expired session could improve user experience when using SATOSA. This could be also a way to introduce a HTML template for 500 error handling.

## Current Behavior
This is the stacktrace regarding the session expiration. As we can read this could be more accurante and eloquent to tell to the sysadmin: "Don't worry, that session is expired...".

````
[2019-04-24 17:26:56] [ERROR]: [urn:uuid:41986301-2e69-4191-8f8f-cd6239316f78] Uncaught exception
Traceback (most recent call last):
  File "/home/user/django-saml2-idp.env/lib/python3.7/site-packages/satosa/base.py", line 286, in run
    resp = self._run_bound_endpoint(context, spec)
  File "/home/user/django-saml2-idp.env/lib/python3.7/site-packages/satosa/base.py", line 228, in _run_bound_endpoint
    return spec(context)
  File "/home/user/django-saml2-idp.env/lib/python3.7/site-packages/satosa/backends/saml2.py", line 246, in authn_response
    return self.auth_callback_func(context, self._translate_response(authn_response, context.state))
  File "/home/user/django-saml2-idp.env/lib/python3.7/site-packages/satosa/base.py", line 185, in _auth_resp_callback_func
    internal_response.requester = context.state[STATE_KEY]["requester"]
  File "/home/user/django-saml2-idp.env/lib/python3.7/site-packages/satosa/state.py", line 230, in __getitem__
    return self._state_dict[key]
KeyError: 'SATOSA_BASE'
[2019-04-24 17:26:56] [ERROR]: Unknown error: 'SATOSA_BASE'
````

## Steps to Reproduce
Start an AuthRequest to SATOSA frontend (use DS to select the IDP if more then one was configured in metadata), then go buy an icecream and take your time to eat it under the spring sun, then go back to put your credentials or give your data consent, then you'll be redirected to SATOSA's backed but... the "Unknow Error" appears.

**Comment by peppelinux** [comment]
Probably also related to https://github.com/IdentityPython/SATOSA/issues/195

**Comment by rhoerbe** [comment]
Reraising most exceptions as "UnknownError" (satosa.base:run) is misleading, because actually the code is masking the real cause. 
The name should rather be something like "System error. The problem cannot be handled by the end user, please contact the system administrator with the error reference <ref code>". <ref code> should be a short string (e.g. a 8-character random value) copied in the log file.
For non-production environments it should be possible to display the real error message via a config setting.

**Comment by peppelinux** [comment]
@rhoerbe I agree,
I'd also like to introduce the opportunity to handle this message within a html template, with a ul/li list of possibile causes, like:

- session timeout
- cookie problem
- others...

Would you agree?

**Comment by rhoerbe** [comment]
I was not so much concerned with the UI but with the correctness of the exception message. I guess that what you need is an additional layer on top of the raw exception message.

IIRC we had a discussion last year wrt the error UI. We talked about delegating the rendering of the error page to some external service to avoid getting stuck with a certain templating system and capability.

- Rainer

**Comment by peppelinux** [comment]
I understand, I went more in the Deep with this PR https://github.com/IdentityPython/SATOSA/pull/221/files to expose the exception message to the users. I thought that a simple Page could be good enough, having the possibility to inherit template filename or configure It in the proxy general config.

Your suggestion instead Is, following the community point of view, to delegate this UI feature to an external web service. Could It be a simple HTML Page with some js functions that takes the exception message from the URL and render It in the DOM?

Or a more complex rest web service?

Both of them should require an additional web resource to be configured in the httpd, wouldn't it be too much overkill? Oop inheritance Just works, isn't so?

Thank you for your share

**Comment by rhoerbe** [comment]
> Am 2019-06-06 um 01:16 schrieb Giuseppe De Marco <notifications@github.com>:
> 
> I understand, I went more in the Deep with this PR https://github.com/IdentityPython/SATOSA/pull/221/files <https://github.com/IdentityPython/SATOSA/pull/221/files> to expose the exception message to the users. I thought that a simple Page could be good enough, having the possibility to inherit template filename or configure It in the proxy general config.
> 
It should be painless to either have a SATOSA-provided error page in solitary installations or delegate it in deployments within existing UI frameworks. SATOSA could provide a simple HTML page as default and allow for  external renderings. Once there is an external option it does not matter if the internal template system is something simple like string.Template or more elaborated.

> Your suggestion instead Is, following the community point of view, to delegate this UI feature to an external web service. Could It be a simple HTML Page with some js functions that takes the exception message from the URL and render It in the DOM?
> 
> Or a more complex rest web service?
> 
> Both of them should require an additional web resource to be configured in the httpd, wouldn't it be too much overkill? Oop inheritance Just works, isn't so?
> 
I would just pass parameters to an error page at a configurable location to avoid any kind of other dependency. To pass parameters I would choose a 307 POST-redirect to get around URL-parameter restrictions.

- Rainer

**Comment by peppelinux** [comment]
As reference for logging
https://docs.python.org/3/library/logging.handlers.html#httphandler

For error representation to users:
I agree your line, we could implement a class to handle this task, the behaviour could be configured in proxy_configuration.yaml.
It could handle It as a Get/Post to third-party ws (if get: in base64 format) or custom internal HTML rendering (passing also the template file).

How many items an error Page should have?
I purpose 3 items:
1. Totale
2. Message
3. Optional description

**Comment by rhoerbe** [comment]
In production mode the 3 items should be fine. The Session UUID from the log could be an extra field instead of packing it into the message, if available.

In a verbose environment with debug enabled it is always nice to show the module path as context.

**Comment by peppelinux** [comment]
Hi R, I did not understand "module path as context" but I can Imagine what you mean.
We can add

4. Message/session id (uuid), optional
5. Context in a collassabile dom item, optional

I would produce a Django app that get these json objects in base64, to represent all this in HTML, once this task Will be approved. You're also a djangoer, we could create this satosa adjunction tool

**Comment by c00kiemon5ter** [comment]
The cookie is now a session cookie; this should not be able to happen anymore.
