### ISSUE TITLE
flagging an ERROR although OK: satosa.state:cookie_to_state:No cookie named SATOSA_STATE

### ISSUE THREAD

**Issue by rhoerbe** [IdentityPython/SATOSA#236]
SAML AuthRequests do not need the state cookie, actually it dos not make sense to read an existing one.

## Expected Behavior
The endpoint module should know if a state cookie is required and raise an exception if it was missing. satosa.state:cookie_to_state should return an empty state object, not raise an exception

As a result ERRORs would only appear in the log if justified.

**Comment by peppelinux** [comment]
@rhoerbe I completely agree with you, I patched this behaviour in my environment.

![Selezione_579](https://user-images.githubusercontent.com/1297620/59421143-680d6b00-8dce-11e9-9f85-1de8965e7d88.png)

**Comment by peppelinux** [comment]
@rhoerbe sorry for the late, I finally made this PR https://github.com/IdentityPython/SATOSA/pull/250 with my proposal

**Comment by c00kiemon5ter** [comment]
Fixed by fcd61a2d13ad6e7a1dd0e8998ae9490d8ef2ce30 and dcec6e57a30d18f9f9502b9725cb603fff229fc7
