### ISSUE TITLE
SAML2 SP backend check scope on attributes and reject by default

### ISSUE THREAD

**Issue by skoranda** [IdentityPython/SATOSA#297]
The SAML2 SP backend should check the scope on scoped attributes asserted by an authenticating IdP and compare with the scope from the SAML metadata for the authenticating IdP and by default reject attributes that have the incorrect scope.

Since SATOSA is a proxy and there are some esoteric use cases where the SAML2 SP backend should consume scoped attributes from an authenticating IdP with the incorrect scope, this behavior should be configurable (with reject being the default).

## Code Version

4.x

## Expected Behavior

The SAML2 SP backend should check the scope on scoped attributes asserted by an authenticating IdP and compare with the scope from the SAML metadata for the authenticating IdP and by default reject attributes that have the incorrect scope.

## Current Behavior

The SAML2 SP backend consumes all attributes from the authenticating IdP (provided there is an appropriate definition in internal_attributes.yaml) and makes them available to microservices.

**Comment by c00kiemon5ter** [comment]
I think this will implemented as a micro-service. The policy on when this is enabled and how it should behave can then be extended without us enforcing those decisions.

We will introduce new internal fields for metadata from the requester and the issuer. These need to be provided by the backends and frontends. Those can be reused by micro-services to extract data for the requester and the issuer. Some internal fields will be removed (ie, requester_name).

A new micro-service will look up the issuer (shibmd) scope(s) (as provided by the previously mentioned new metadata fields) and compare it(them) against the values of the configured internal attributes. Non matching values will be dropped.

**Comment by vladimir-mencl-eresearch** [comment]
Hi,
Is the SATOSA SAML backend the right place to handle this?  I'd expect this should really be part of pysaml2's functionality .... ?

Cheers,
Vlad

**Comment by c00kiemon5ter** [comment]
At this point, this is an arbitrary computation on the attributes, so this belongs to the micro-services. PySAML2 could be doing this, but then it would need to know whether attributes are scoped and then apply some filtering. Apart from that being more complex it is also less flexible. Micro-services can be extended by other users easily.
This does not preclude having the same feature on pysaml2. It can as well be implemented in both places. But it is trivial to do it as a micro-service.

**Comment by c00kiemon5ter** [comment]
To expand a bit more on this; having this functionality as part of a micro-service means that it runs for both SAML and OIDC (and other protocols, if/when implemented). There is an assumption that in OIDC the only claims available are the ones defined by the core specification, but in practice there are many custom claims available and within the academia space these are now closely resembling the SAML attributes. In fact the attribute profiles/specifications are getting more data-centric and less protocol-centric - the same profiles can be applied to ADFS, SAML and OIDC. This this issue is already there for those protocols too.

**Comment by vladimir-mencl-eresearch** [comment]
Thanks for the clarification - considering it applies not only to SAML but also to OIDC, it makes sense to do it in SATOSA.

I initially thought of it as a core SAML thing to do (well, built on top of the shibmd extension) - but something SAML SP should do, not the app behind it.

But with the absence of this functionality in pysaml2, and with OIDC also needing it, a microservice in SATOSA sounds as the right approach.

**Comment by c00kiemon5ter** [comment]
Another thing to keep in mind is that there more considerations regarding semantics of other attributes; upstream IdP identifiers may need to be communicated downstream. This usually happens through the voPersonExternalID attribute and it means that if this attribute is to be released it should get the IdP-scoped attributes and forward them as they are. This type of semantics, dependency and ordering of computations, are hard to implement in a library without complex configuration and the need to pass downwards more context about these transactions.

**Comment by nckroy** [comment]
Watching this issue because it's a significant security concern. See also: https://www.economyofmechanism.com/office365-authbypass.html

**Comment by vladimir-mencl-eresearch** [comment]
... and this has now been released in 8.3.0 (and 8.4.0)
