### ISSUE TITLE
Accessing data from SP

### ISSUE THREAD

**Issue by colorado963258** [IdentityPython/SATOSA#321]
Hello, I have a short question about microservices.
I am playing with SATOSA and I am creating a microservice. In this microservice I need to access data sent from the SP, specifically whether SP requested multi-factor authentication, could you please tell me how to get this information in ResponseMicroService? I was only able to find out that IdP did SFA.

If it is not possible to get this information in the ResponseMicroService, is it at least possible in the RequestMicroService because I wasn't able to find it there either?

Thank you for any help.

**Comment by c00kiemon5ter** [comment]
Hello,

currently this information is not available in the backend. But, it is something that has come up in the past, and should be an easy thing to do as a contribution. The Context can be used to hold this information. The SAML frontend can be keeping this information and the SAML backend can be configured to use it or ignore it.

Would you like to give this a try?

**Comment by c00kiemon5ter** [comment]
See #328
