### ISSUE TITLE
Question: Is there support for multiple KeyDescriptor elements in SAML IdP Metadata?

### ISSUE THREAD

**Issue by JP-Dhabolt** [IdentityPython/SATOSA#334]
## Code Version
7.0.1

## Expected Behavior
When performing a key rotation, a common practice is to include multiple `<KeyDescriptor use="signing">` elements, one for the existing key cert, and one for the future key cert.  Once the metadata has been updated in every SP, the key rotation can then be performed without any downtime, and without having to coordinate an exact rotation time.

## Current Behavior
Looking through the documentation and code, I cannot find any information as to whether this is possible (hence the question).  I appreciate any guidance here as to whether this is currently possible, or would need to be a feature request.

## Possible Solution
N/A

## Steps to Reproduce
N/A

**Comment by ioparaskev** [comment]
Hello,

Sorry for the delay but the answer is yes (at least it's good news :smile: )
You can achieve this through setting the `additional_cert_files` option in the frontend config.
i.e
```yaml
module: satosa.frontends.saml2.SAMLFrontend
name: Saml2IDP
config:
  idp_config:
    additional_cert_files: ["/home/admin/saml2_frontend.crt"]
```
This option is defined in the [pysaml configuration docs](https://pysaml2.readthedocs.io/en/latest/howto/config.html#additional-cert-files).It mentions that the certificates should be pem formatted which actually means that they should follow the ASCII PEM format (not necessarily having a `.pem` extension). (It might be confusing for some people to think that they should use `.pem` files so I figured I should clarify this).
This will result in metadata generated with multiple KeyDescriptors

**Comment by JP-Dhabolt** [comment]
Thanks for the response.  That's great news!  This drastically simplifies our coordination effort for future cert rotations.

I appreciate your response, and your contributions to this app, which has been very useful thus far.
