### ISSUE TITLE
oidc-frontend: email claim not part of userinfo

### ISSUE THREAD

**Issue by ctr49** [IdentityPython/SATOSA#343]
## Code Version
7.0.1

## Expected Behavior
email claim being part of userinfo

## Current Behavior
email claim not part of userinfo

## Steps to Reproduce

1. Setup oidc-to-saml proxy as per instructions
2. Get access token, fetch userinfo

For some reason the email claim (also being defined in the standard profile) is not returned by the userinfo endpoint.
I already enabled some additional debugging (see #342 ) and can observe the 'mail' attribute coming from SAML
`[satosa.attribute_mapping]: backend attribute ['mail'] mapped to mail (['vorname.nachname@provider.de'])`
and also this being mapped to the fronted:
`[satosa.attribute_mapping]: frontend attribute email mapped from mail (['vorname.nachname@provider.de'])`
but email ist not part of the returned object when fetching userinfo.

The (oidc frontend) provider is configured to support openid, profile, email

**Comment by Torrien** [comment]
I am having this same issue. Do I need to configure some type of permission for the client to have the email and name delivered?

**Comment by vladimir-mencl-eresearch** [comment]
Hi, what scopes do you request in the OIDC request?  The `openid` and `profile` scopes do not include the `email` claim, you have to explicitly request also the `email` scope to get the `email` claim.

Hope this helps.

Cheers,
Vlad

**Comment by Torrien** [comment]
@vladimir-mencl-eresearch Thanks for the update. And yes, I got to this solution earlier in the week. 

I had to add `extra_id_token_claims` for this to work. The email was already being mapped to internal attributes but not being delivered to the client. By adding `email` as an extra_id_token_claim for the specific client_id the attribute was delivered.

**Comment by vladimir-mencl-eresearch** [comment]
Hi @Torrien ,
In my deployment, I configure clients in a cdb.json file which is referred to by name in the frontend config file (as `client_db_path`).

As for passing the email, you should be able to access it via the `email` scope without having to configure `extra_id_token_claims` (which should however work as well).
I've just checked and in `oic/message.py`, the `email` scope is mapped to the `email` and `email_verified` claims.
(However, it expects exactly these claim names, so it would not work if your `mail` attribute has an `openid` name different from `email` in `internal_attributes.yaml`.

Hope this helps.

Cheers,
Vlad

**Comment by bds-congnguyen** [comment]
Hi @vladimir-mencl-eresearch , 
sorry for comment in closed ticket but I'm getting the same issue, I've spent few days to research around but didn't find solution yet.
my `internal_attributes.yaml` file is
```
attributes:
  email:
    openid: [email]
    saml: [email]
  mail:
    openid: [email]
    saml: [email, emailAddress, mail]
  name:
    openid: [name]
    saml: [name]
```
and in log show
```
[2023-05-09 15:03:14,580] [DEBUG] [satosa.attribute_mapping.to_internal] backend attribute ['email'] mapped to email (['<redacted>'])
[2023-05-09 15:03:14,580] [DEBUG] [satosa.attribute_mapping.to_internal] backend attribute ['email', 'emailAddress', 'mail'] mapped to mail (['<redacted>'])
[2023-05-09 15:03:14,581] [DEBUG] [satosa.backends.saml2._translate_response] [urn:uuid:582b5d27-bb86-48d6-ba24-939e9dc3d724] backend received attributes:
{
    "id": [
        "0C15exNS7B<redacted>LnISbJEk5mcPoXic2rM"
    ],
    "email": [
        "<redacted>"
    ],
    "name": [
        "<redacted>"
    ],
    "groups": [
        ""
    ]
}

[2023-05-09 15:03:14,581] [DEBUG] [satosa.routing.frontend_routing] [urn:uuid:582b5d27-bb86-48d6-ba24-939e9dc3d724] Routing to frontend: OIDC
[2023-05-09 15:03:14,581] [DEBUG] [satosa.attribute_mapping.from_internal] frontend attribute email mapped from email (['<redacted>'])
[2023-05-09 15:03:14,581] [DEBUG] [satosa.attribute_mapping.from_internal] frontend attribute email mapped from mail (['<redacted>'])
...
[2023-05-09 15:03:14,771] [DEBUG] [pyop.authz_state._create_access_token] creating access token for scope=openid profile email groups
[2023-05-09 15:03:14,786] [DEBUG] [pyop.provider._do_code_exchange] issued id_token=<redacted> from requested_claims={} userinfo={} extra_claims={}
```
so based the log above the `userinfo` is {} empty, and when I decode JWT token it also show only `openid` 

Could you help/guide me resolve this issue?

**Comment by bds-congnguyen** [comment]
okay, after checked source code I noticed that the response type `code` will return only `oidc` claim, so for userinfo data will also need `id_token`. so I changed config in `cdb.json` file from
```
"response_types": ["code"],
```
to 
```
"response_types": ["code", "id_token"],
```
and now userinfo is returned as expected.

**Comment by c00kiemon5ter** [comment]
@bds-congnguyen the proper flow is to
- request a `code`
- exchange it for an `id_token` and `access_token` on the token endpoint
- use the `id_token` to create a session
- use the `access_token` to invoke the userinfo endpoint and get information about the user
