### ISSUE TITLE
Docker Image is really big

### ISSUE THREAD

**Issue by shaardie** [IdentityPython/SATOSA#350]
## Code Version
Satosa Docker Image v7.0.3 (current latest)

## Expected Behavior
Docker Images should be small, since it is then easier to work with them and they have in general a smaller attack surface.

## Current Behavior
The Docker Image is quite big, see

```bash
$ docker images satosa/satosa
REPOSITORY      TAG       IMAGE ID       CREATED       SIZE
satosa/satosa   latest    e4233e2ef414   12 days ago   428MB
satosa/satosa   v7.0.3    e4233e2ef414   12 days ago   428MB
```

## Possible Solution
There are several smaller things that can be done, like removing the `/src` directory from the image again.
I would suggest not using Debian, but Alpine as a base and maybe also use a [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/) or use PyPi for statosa installation.

We are currently building our own image using Alpine and PyPi and have an Image with `86MB`.

I would be happy to help with that. So let's discuss what would be a good solution for you.

## Steps to Reproduce

```bash
$ docker pull satosa/satosa:v7.0.3
$ docker images satosa/satosa
```

**Comment by peppelinux** [comment]
I completely Agree, my demo SATOSA Dockerfile with Alpine is here:
https://github.com/UniversitaDellaCalabria/Satosa-Saml2Spid/blob/master/Dockerfile

**Comment by c00kiemon5ter** [comment]
Hello,

satosa is a complex system. Users will most probably need to have their own plugins and wire up the system in a way that complies with their use case. Additionally, they will need to control the environment (versions, dependencies, host settings like the network, etc). Thus, I don't aim to have the upstream satosa image be "the" image people should use - it should primarily be used as an example.

Having said this, I do want to fix several aspects of the docker image:
- switch gunicorn for uwsgi and allow users to provide a proper config
- fix permissions and remove roor user
- separate the build-phase that needs network
- tidy up the host-dependencies and app-dependencies
- manage files better
- turn the image into a multi-stage build
- use a proper entrypoint and cmd
- fix logging
etc.

I don't really mind about the size, but it would be nicer to make the image slimmer (it will happen). What the base image will be, is debatable. Debian is nice as it provides a good common ground for most people.

Do keep in mind, that this is not a high priority item for me, right now.

**Comment by c00kiemon5ter** [comment]
Putting a note here too;

Work is being done on this aspect under https://github.com/IdentityPython/satosa-docker following the "Docker Official Images" guidelines. Soon, we will remove the Dockerfile from this repo and all related information about Docker and the image will move there.

I will close this issue and I would urge you to open a new issue or new PR there, if the issue persists. While this issue is focused mainly on the size of the image, more aspects will be changing. Thanks for your understanding!


/cc @xenophonf

**Comment by niheconomoum** [comment]
Dear @shaardie, thank you so much for this suggestion!

SATOSA has recently been accepted into the Docker "Official Images" library:
https://hub.docker.com/_/satosa
https://github.com/IdentityPython/satosa-docker

The new images are much smaller than the previous iteration:
```bash
$ docker images satosa
REPOSITORY   TAG        IMAGE ID       CREATED      SIZE
satosa       alpine     7cb5fe08aeff   5 days ago   110MB
satosa       bullseye   31d2ea2bf9e0   5 days ago   222MB
```

Please let me know if this doesn't meet your needs or if something doesn't work.
