### ISSUE TITLE
Multi-value attributes i OIDC->SAML

### ISSUE THREAD

**Issue by nicemid** [IdentityPython/SATOSA#85]
If we have a OpenId frontend and a SAML backend where the IDP returns several attributes with the same name, then SATOSA will only be able to map the first attribute to a single claim value. It should map the attributes to a claim with an array of values.

The problem in the code are: satosa/frontends/openid_connect.py
`self.user_db[internal_resp.user_id] = {k: v[0] for k, v in attributes.items()}`

**Comment by peter-** [comment]
AFAICT that code and issue doesn't exists anymore (6 years later).  
Does anyone care to close this issue?
