### ISSUE TITLE
debug mdq support for saml_frontend (idp)

### ISSUE THREAD

**Issue by leifj** [IdentityPython/SATOSA#90]
specifying metadata as an MDQ doesn't work for an IdP. Since metadata lookup comes after the discovery phase (when you have >1 IdP) there is no reason it shouldn't work.

**Comment by peppelinux** [comment]
Ho @leifj I get It to work this way
https://github.com/peppelinux/Satosa-saml2saml/blob/master/example/plugins/frontends/saml2_frontend.yaml

Did I understand this issue? Something sounds unclear to me, my excuses in advance
